spring:
  config:
<<<<<<< HEAD
    import: security.yml
=======
    import: security-variable.yml
>>>>>>> develop
  application:
    name: MovieCrew
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/moviecrew
    username: root
    password: ${mysql.password}
  thymeleaf:
    cache: false
  mvc:
    static-path-pattern: /static/**
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
<<<<<<< HEAD
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
=======
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  movie:
    api:
      url: https://api.themoviedb.org/3
      key: 00d39ce433d4e05bacd8d3b68be6ef40
>>>>>>> develop
